### ISSUE TITLE
index.html under example_project imports incorrectly

### ISSUE THREAD

**Issue by rakshakhegde** [Polymer/vscode-plugin#11]
The [example_project/index.html](https://github.com/Polymer/vscode-plugin/blob/master/client/example_project/index.html) imports incorrectly like so:
`<link rel="import" href="../paper-button/paper-button.html">`

But the bower_components will be installed in the same folder. So this is the correct import for `paper-button` and `paper-spinner`:
```
<link rel="import" href="bower_components/paper-button/paper-button.html">
<!-- Oops, this import is *still* misspelled.. -->
<link rel="import" href="bower_components/paper-spinner/paper-spanner.html">
```

Shall I PR or is this intentional?

**Comment by rictic** [comment]
This is intentional. If you open the base directory directly, it will work. We might make this more flexible in future.

Making ../ reference bower components is a key part of the modular components development story.

**Comment by rakshakhegde** [comment]
Sweet, that's convenient. But that also signifies quite the commitment to Bower, doesn't it? 😅
Anyways that requires documentation. I'll go ahead and add comments to that file.

**Comment by rakshakhegde** [comment]
#13

**Comment by rictic** [comment]
We'll also do the right thing for node_modules, once we've resolved what that right thing is.
