### ISSUE TITLE
Clicking Properties or Behaviors in Javascript does not jump to source line

### ISSUE THREAD

**Issue by rakshakhegde** [Polymer/vscode-plugin#14]

**Comment by Boltarok** [comment]
I'm using the lastest version (0.1.1) and this isn't working jet, when i press F12 in some property, i get this error:
![image](https://cloud.githubusercontent.com/assets/14010175/19732030/d22511da-9b75-11e6-93c3-7492d232425f.png)

**Comment by rictic** [comment]
@boltarok, your issue is separate from this one. Filed as #35.

**Comment by rictic** [comment]
Our current plan for pure javascript stuff like jumping to definition in JS is to recommend using another plugin for static analysis of code. We may support this at some point, but not in the near to medium term. There's already so many good tools for this like tern.js and typescript.
