### ISSUE TITLE
Output window stealing focus

### ISSUE THREAD

**Issue by NvGary** [Polymer/vscode-plugin#15]
A syntax error results in the output window opening and receiving keyboard focus, where the following error is reported:
`[Error - 20:47:55] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Unexpected token {
  Code: -32603`
Only occurs when the Output window is not visible to begin with.

**Comment by rictic** [comment]
#10 covers the pop-up but I'm surprised that an unexpected token would cause an error. Would you mind pasting in or linking to the document where this error appears?

**Comment by NvGary** [comment]
It's important to begin with the Output window hidden, else the issue cannot be reproduced.

![image](https://cloud.githubusercontent.com/assets/20575225/19517392/dcea747a-95f8-11e6-9b9b-8b815cfbfe09.png)
In this example I selected the `if` and started retyping with `i` (line.4) and the Output opens with the error shown and steals focus. Contrived example but it does reproduce the issue.

Closing the Output window leads to a hover error, and again the Output window opening and stealing focus once more.

**Comment by quangld** [comment]
I confirmed this problem. Just create a blank .js file, and type **const a**, should give out this error. SyntaxError is thrown from espree.parse but the extension is unable to catch it for some reason

**Comment by rictic** [comment]
Ah, right. Got it. I'll have a PR to fix by this evening.

**Comment by NvGary** [comment]
No longer an issue in v0.1.2

**Comment by rictic** [comment]
Still getting reports of this, from e.g. https://github.com/Polymer/polymer-editor-service/issues/26

Reopening.
