### ISSUE TITLE
Plugin doesn't handle windows file paths

### ISSUE THREAD

**Issue by rasto68** [Polymer/vscode-plugin#17]
I used polymer cli to create a new element and then opened the folder in vscode, it looks like polymer ide is including the windows drive letter twice in the file paths:
![polymer-ide](https://cloud.githubusercontent.com/assets/3791099/19509769/3d4f9ce4-95d8-11e6-813a-bb057e678e3d.png)
This breaks the 'click to open file' functionality

**Comment by benhjt** [comment]
See https://github.com/Polymer/vscode-plugin/issues/9

**Comment by rictic** [comment]
Dup of #9

**Comment by rictic** [comment]
Turns out the editor plugin seems to be fine with windows paths, and this is a local bug (and apparently we've got similar bugs in the atom and sublime text plugins).

Reopening
