### ISSUE TITLE
Usage of `../`  when VSCode opened in a multi-project folder

### ISSUE THREAD

**Issue by LostInBrittany** [Polymer/vscode-plugin#18]
As the PR #13 says, the `../` defaulting to `bower_components` is a key part of the modular/web components development story, and PRs #13 and #16 deal with some of the problems... but not all of them.

I have many Polymer projects, one for each element, under a father folder `polymer`. In order to work efficiently in vscode, I don't open a new instance for each element, but I use only an instance of vscode opened on `polymer` folder, like this:

<img width="883" alt="001" src="https://cloud.githubusercontent.com/assets/726476/19519156/f2995d38-960a-11e6-8c0b-58e63cbadf3d.png">

And in this setup, `../` doesn't default to  `bower_components` at the root of every project.

<img width="884" alt="002" src="https://cloud.githubusercontent.com/assets/726476/19519265/7c9db2cc-960b-11e6-8101-c8d263d95389.png">
 
I guess the problem is that the plugin is only defaulting `../` to  `bower_components` if we are at the workspace root. A saner way to do it (in my opinion, maybe I'm very wrong :) ) would be looking for `bower_components` at each step.

I don't know if the problem is clearly explained...

**Comment by rictic** [comment]
See also: https://github.com/Polymer/polymer-editor-service/issues/2

It's possible that having multiple workspace roots adds some complexity here? But maybe not

**Comment by LostInBrittany** [comment]
I would love multiple workspace roots!

But we could begin with something simpler: if the current folder has a `bower_components` folder on it, use it instead of sibling folder when doing `../`.

What do you think of this idea?

**Comment by rictic** [comment]
Opened #19 for multiple workspace roots. The `../` issue affects all editors, so let's discuss it further at https://github.com/Polymer/polymer-editor-service/issues/2
