### ISSUE TITLE
Provide intellisense / go to definition for event handlers

### ISSUE THREAD

**Issue by bahrus** [Polymer/vscode-plugin#20]
Pretty self explanatory, but <my-component on-click="

At that point, would be great if it could fine all methods and provide autocomplete.  And to be able to F12 on an existing method and jump to the code.

**Comment by rictic** [comment]
Moved to polymer-editor-service as this is something that we can implement there to help all editors, not just vscode. I don't think that there would even need to be any vscode specific code to make this work, once the editor service grows this capability it'll automatically come to our vscode plugin.
