### ISSUE TITLE
Installing missing bower elements will not refresh analyser and it will continue to showing the error

### ISSUE THREAD

**Issue by LostInBrittany** [Polymer/vscode-plugin#22]
It's the same problem that in [atom plugin](https://github.com/Polymer/atom-plugin/issues/19)

@jarrodek reported:
> When I `<link>` import some element that is not present in `bower_components` directory the plugin will display error as it should. However, after I `bower` this element and it's already available in the path the plugin will continue to display error about missing file. 
I tried to modify name of imported element and back, remove the line, save and add the line again and nothing changed. After I restarted the editor it finally accept that there's the element.

> I'm guessing that the information about missing file is cached somewhere and it's not updated after missing file appear. Plugin should inform the analyser that there was a change in files (especially missing files) and should re-run the analysis.

I'm guessing it's also a problem for Sublime, even if I haven't tested as I haven't been able to make the plugin on Sublime yet :)

Maybe it should be reported in the `analyzer` side?

**Comment by rictic** [comment]
Yeah, this is probably best reported on polymer-editor-service. I'll move these issues over.

**Comment by rictic** [comment]
Making https://github.com/Polymer/polymer-editor-service/issues/14 the canonical bug.
