### ISSUE TITLE
Document types supported by extension

### ISSUE THREAD

**Issue by peterblazejewicz** [Polymer/vscode-plugin#25]
I"m getting this error frequently:
```
[Error - 9:14:41 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: No parser for for file type 
  Code: -32603 
```
That's not a problem that I'm seeing that error - but the problem is that I'm getting it in files like `.gitignore` - just because the `.gitignore` contains an url:
```
# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt
```
Somehow extension works with  `.gitignore` and whenever an url in text is focused (via mouse) the error appears.

As I understand the extension should be configurable somehow to support only related types of documents.

Thanks!

```
Version
0.1.0
```

**Comment by rictic** [comment]
Huh, that's weird. It should only be paying attention to html, js, and css files. Oh! I still have plaintext as a supported type. I'll remove that.
