### ISSUE TITLE
@apply coloring is wrong

### ISSUE THREAD

**Issue by akc42** [Polymer/vscode-plugin#34]
Not sure if this is polymer-ide or not, but in my css I have a number of `@apply` for flex layout.  The first one (in a `:host` selector) is fine, all the others are colored white, except for the 'y' which is colored blue
(I am using the monokai theme).

The `@apply` in the `:host` selector doesn't color the `--layout-vertical` blue whereas it does in all the others occurances.

**Comment by rictic** [comment]
Would you mind including a screenshot?

**Comment by akc42** [comment]
![screenshot_gitub_vscode-plugin 34](https://cloud.githubusercontent.com/assets/368238/19777683/518add78-9c71-11e6-8c2d-b18d1b3455cf.png)

**Comment by rictic** [comment]
So I looked into this a bit more, this is an issue with the the css tmbundle grammar. I think https://github.com/textmate/css.tmbundle/issues/27 is the canonical issue.

We don't ship any syntax highlighting as part of this plugin, and I think upstream is the proper place to fix this.
