### ISSUE TITLE
Jump to definition not working with paths that need url-escaping

### ISSUE THREAD

**Issue by rictic** [Polymer/vscode-plugin#35]
> @Boltarok said in https://github.com/Polymer/vscode-plugin/issues/14#issuecomment-256379286
> 
> I'm using the latest version (0.1.1) and this isn't working jet, when i press F12 in some property, i get this error:
> ![image](https://cloud.githubusercontent.com/assets/14010175/19732030/d22511da-9b75-11e6-93c3-7492d232425f.png)

Looks like this is the inverse of #16

**Comment by quangld** [comment]
Confirmed.
The getUriForLocalPath returns **file://**c:\... instead of **file:///**c:\
So a forward slash is missing the the path for Windows environment.

**Comment by rictic** [comment]
This should be fixed by https://github.com/Polymer/polymer-editor-service/pull/45 which was released in v0.4.0
