### ISSUE TITLE
Ignore protocol-relative URI paths (e.g. for Google Fonts) instead of evaluating them to local resource

### ISSUE THREAD

**Issue by peterblazejewicz** [Polymer/vscode-plugin#38]
When relative path is used for external resource like Google Fonts:
```html
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Raleway:400,700">
```
the plugin mark the url as invalid:
```
file: 'file:///Users/piotrblazejewicz/git/vaadin-angular-polymer/polymer/index.html'
severity: 'Error'
message: 'Unable to load import: ENOENT: no such file or directory, open '/Users/piotrblazejewicz/git/vaadin-angular-polymer/polymer/fonts.googleapis.com/css''
at: '73,33'
source: 'polymer-ide'
```
I know protocol-relative is the anti-pattern now: https://www.paulirish.com/2010/the-protocol-relative-url/ 

Thanks!

**Comment by rictic** [comment]
+1 thanks for the bug report. This is an analyzer-level bug. Moved to https://github.com/Polymer/polymer-analyzer/issues/382 - please follow it there.
