### ISSUE TITLE
Still seeing path issues with Windows

### ISSUE THREAD

**Issue by bahrus** [Polymer/vscode-plugin#40]
I saw some earlier issues raised and closed.  I was hoping the latest version (0.2.0) would fix for me, but no such luck.  

I have a file in the root directory called [animationTest.html ](https://github.com/bahrus/crystal/blob/master/animationTest.html) which references a polymer 1 -based custom element called xtal-prep.  animationTest.html has a single import line:
```html
<link async rel="import" href="animationRefs.html">
```

That file imports the definition for xtal-prep among others:

```html
<link rel="import" href="xtal-elements/xtal-prep.html">
```

When I right click on 

```html
<xtal-prep></xtal-prep>
```
in animationTest.html,  and select Go to Definition, I get error 

"Unable to open 'xtal-prep.html': File not found (\\\\c:\git\crystal\xtal-elements\xtal-prep.html)."

Something is causing the insertion of two slashes before the c: , for some reason.

**Comment by Inrego** [comment]
I just came here to report the same thing.

**Comment by skropos** [comment]
Same problem here. Thank you

**Comment by 200Puls** [comment]
I just noticed the same problem. Unable to open 'element.html': File not found (\\c:\...\src\element.html).

**Comment by rictic** [comment]
Just stamped and published v0.4.0 which includes https://github.com/Polymer/polymer-editor-service/pull/45 that I believe fixes this issue, at least on my local windows box.

Anyone want to try it out and confirm?

**Comment by bahrus** [comment]
Tried it.  My original issue is now resolved.  Woo hoo!  I'll keep testing and report any other issues I encounter.

**Comment by rictic** [comment]
Awesome! The next release will improve path handling further (we're moving to use the same library as VSCode uses to manage paths and URIs) but I believe 0.4.0 should fix the vast majority of path issues.

**Comment by skropos** [comment]
i looks good !! thanks @rictic
