### ISSUE TITLE
href='//...'

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/vscode-plugin#41]
<link rel='stylesheet' href='//fonts.googleapis.com/css?family=RobotoDraft:regular,bold&amp;lang=en'>

![image](https://cloud.githubusercontent.com/assets/863731/20984555/156be6c8-bcc1-11e6-8ed5-3a506f2e4b72.png)

should be ignored by ide

**Comment by rictic** [comment]
Agreed, and thanks for filing. The root cause is this bug: https://github.com/Polymer/polymer-analyzer/issues/382

Please follow there for updates
