### ISSUE TITLE
0.3.0 - 0.4.0 are not marked as released in GitHub

### ISSUE THREAD

**Issue by tony19** [Polymer/vscode-plugin#51]
Minor: The GitHub releases tab lists 0.3.0 and 0.3.1 as "unreleased" tags (I think that's the correct term), and 0.4.0 is not listed at all. Is this intentional?

![screen shot 2017-02-26 at 2 48 43 pm](https://cloud.githubusercontent.com/assets/26580/23343549/f489a81c-fc32-11e6-9e14-e48338c96eb0.png)

**Comment by rictic** [comment]
No particular reason, I just haven't been paying attention to it. Copied over the relevant sections of the CHANGELOG and added the missing v0.2.0 tag.

Thanks for pointing this out!
