### ISSUE TITLE
Navigation / auto complete not working for a slightly unorthodox scenario

### ISSUE THREAD

**Issue by bahrus** [Polymer/vscode-plugin#56]
I'm doing a bunch of unorthodox things here.  Don't know what exactly is the culprit, but

[this page](https://github.com/bahrus/xtal/blob/master/tests/x-slick-grid/example1a-component.html#L30)

is not giving navigation or autocomplete support.  [This page](https://github.com/bahrus/xtal/blob/master/tests/x-slick-grid/example1-simple.html#L14) does.

Let me know if I need to tear things down to find the pattern, or if it is easy to diagnose.

**Comment by rictic** [comment]
We don't follow imports inside of templates. Once https://github.com/Polymer/polymer-analyzer/pull/543 lands you'll be able to add `<link rel="lazy-import" href="whatever.html">` at the top of the page to let the tools know that you'll be importing them at some later point (in your case it seems when the element is first attached).

**Comment by bahrus** [comment]
Good to know.  I moved the imports out of the template.  Still no luck.  Probably something else I'm doing strange.

I'll try getting the linter working to see if that catches anything.

**Comment by bahrus** [comment]
After installing the linter, it does give warnings if I move the imports inside a template (even though it happened to work during runtime.

What it didn't catch I don't think was I opened the template with 

<dom-lite>

and closed it with 

</dom-module>

My bad, obviously.  I guess I need a linter that catches invalid HTML.  🤕

Does the polymer linter catch that, or do I need a separate extension?

**Comment by rictic** [comment]
The polymer linter uses an htm5 parser, so by the time we see the HTML it has already had the html error handling algorithm run over it. Using htmlhint or similar is best for that sort of error.
