### ISSUE TITLE
doesn't add ',' when adding closing '}' of a function

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/vscode-plugin#67]
If I type `myFunct() {`, it'll add a closing `}`, but it won't add `,` after it, which I always have to add manually, which is annoying.
I suppose this might be a configuration issue...please enlighten me if it is.

**Comment by justinfagnani** [comment]
I don't think this has anything to do with the Polymer IDE plugin, but with VS Code's JS language support.

**Comment by rictic** [comment]
Recommend filing this bug here: https://github.com/Microsoft/vscode/issues
