### ISSUE TITLE
not working on vscode 1.13.0

### ISSUE THREAD

**Issue by pdgago** [Polymer/vscode-plugin#70]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063

Snippets and Intellisense stopped working. Disabling the plugin make it works again.

https://github.com/Microsoft/vscode/issues/28417

**Comment by rictic** [comment]
Can not reproduce
