### ISSUE TITLE
Include syntax highlighting

### ISSUE THREAD

**Issue by pdesjardins90** [Polymer/vscode-plugin#74]
A proper IDE plugin should include syntax highlighting. 

I know there's a [polymer-syntax](https://github.com/JonathanWolfe/language-polymer) plugin that already exists, but it requires to change the *.html file association to a "polymer" language., which makes all html files not work with other html-specific plugins (formatters, etc.). 

Could the polymer-ide plugin "augment" the html syntax highlighting somehow?

**Comment by odahcam** [comment]
Maybe https://marketplace.visualstudio.com/items?itemName=bierner.lit-html is a good option?

**Comment by pdesjardins90** [comment]
it is now yes, thanks!
