### ISSUE TITLE
Suppress specific warnings?

### ISSUE THREAD

**Issue by kaspnilsson** [Polymer/vscode-plugin#78]
Hi! Big fan of this plugin.

I have a lot of warnings in my project that look like this:
`[polymer-ide] ScannedBehavior has both HTML doc and JSDoc comments.`

I'd like to suppress them, but I can't find anywhere to do that. Is this supported at all?

**Comment by rictic** [comment]
Yeah, this is supported.

Run `polymer lint` to see the error code that you're interested in. In this case it's `multiple-doc-comments`. Then just add that to your `polymer.json`'s lint.ignoreWarnings section. So e.g.

```json
{
 "lint": {
    "rules": ["polymer-2-hybrid"],
    "ignoreWarnings": ["multiple-doc-comments"]
  }
}
```

In the current version you'll need to reopen the workspace. In the upcoming version we'll notice changes to polymer.json immediately.

**Comment by rictic** [comment]
Actually, this... may only be supported in the upcoming version. Should come out this week!
