### ISSUE TITLE
Work with refereces to external url's (like CDN)

### ISSUE THREAD

**Issue by bahrus** [Polymer/vscode-plugin#85]
Custom Elements aren't recognized if reference comes from CDN url.

**Comment by rictic** [comment]
Interesting. Yeah, that's doable. I suppose from a caching perspective we should assume that such files never change?

**Comment by rictic** [comment]
All that would be necessary is writing a wrapper for FsUrlLoader that can detect http/https urls and return the bytes of the result, otherwise deferring to FsUrlLoader

**Comment by rictic** [comment]
This issue was moved to Polymer/polymer-editor-service#95
